### PR TITLE
Added delete operation

### PR DESCRIPTION
**Pull request by cbigsby**
Hi Harald,

I implemented deleting data from the cache. It's all fire-and-forget so there's no async. I still have to update the Sample projects, but the functionality and tests are done. Please take a look and let me know if there's anything I should change.

Great library by the way.

### CODE REVIEW

**Comment by cbigsby** [comment]
I've added the additions to the Sample project.

**Comment by Ulriksen** [comment]
Thanks! I'll have a look at it later today.

**Comment by Ulriksen** [comment]
I had forgotten all about the pattern matching or Redis PubSub, so two channels are perfectly fine, but we could get away with one subcription to redis.  http://redis.io/topics/pubsub.

**Comment by cbigsby** [comment]
That is a good point about preserving message order.

My initial aversion to adding a new property to the `CacheUpdateNotificationArgs` is that it could break backwards/forwards compatibility if you did a staged rollout, though I did not test it and that is not a problem that I have.

I can make a branch which uses a single channel and submit it as a separate pull request. We can compare the two and see which is better.

**Comment by cbigsby** [comment]
I'm not sure I understand your pattern matching comment. I think you mean to say in `RedisSubscriber` we subscribe to "cache*" and in the handler call `CacheUpdated()` or `CacheDeleted()` based off the channel name. Thus, there would still be 2 publishing channels, but only a single subscribing channel.

Reading the PubSubOrder doc from StackExchange.Redis I think there might not be a message-ordering problem. It discusses sequential or parallel message processing from *the same connection*, so it sounds like DoubleCache's `ConnectionMultiplexer` will receive, and process, the messages in the order that Redis sends them regardless of if it's one channel or two.

**Comment by Ulriksen** [comment]
Yes, flag is not an option. Should have seen that myself, had message version problems a few months ago. 

On the single/vs double subscriber you got my thinking. As I read the StackExchange and Redis documentation, I belive messages will be ordered from Redis, but the StackExchange client by default will not wait for the completion of the Action handler passed to the Subscribe method. I.e. the "order" or completion of the CacheUpdated method in RedisSubscriber.cs will not be guaranteed. This leaves me with two questions. 

1. Is message ordering important when dealing with cache updates? 
2. If we have two channels for publishing but one subscription for

**Comment by cbigsby** [comment]
1. I think that message ordering is important, as you may have cached data that is dependent on other data that might also be cached, eg: a playlist will have songs.

2. From reading the StackExchange.Redis sources I'm 99% sure that message ordering is per-connection, not per-subscriber, and done serially. I will do a couple tests tonight to make sure

**Comment by cbigsby** [comment]
I wrote this test to see whether separate channels were processed in-order. I tried massaging a few things, like making subscription and publishing async or not, changing the sleep time, etc, and they all were done in-order.

```
[Fact]
public void Subscribe_MessagesProcessedInOrder()
{
    var strings = new List<string>();
    var subscriber = _fixture.ConnectionMultiplexer.GetSubscriber();

    subscriber.Subscribe("Test1", (channel, msg) => { Thread.Sleep(1000); strings.Add("Test1"); });
    subscriber.Subscribe("Test2", (channel, msg) => strings.Add("Test2"));

    subscriber.PublishAsync("Test1", "");
    subscriber.PublishAsync("Test2", "");
    subscriber.PublishAsync("Test1", "");
    subscriber.PublishAsync("Test2", "");
    subscriber.PublishAsync("Test2", "");
    subscriber.PublishAsync("Test1", "");

    Thread.Sleep(4000);

    strings.ShouldBe(new[]{ "Test1", "Test2", "Test1", "Test2", "Test2", "Test1"});
}
```

If I add the line `_fixture.ConnectionMultiplexer.PreserveAsyncOrder = false;` then `strings` has all the "Test2"s first, followed by the "Test1"s. I get the same result if I create a second `ConnectionMultiplexer` and subscribe to the "Test2" channel using the second muxer.

**Comment by Ulriksen** [comment]
@cbigsby thank you so much for your contribution.

**Pull request closed without merging**
